name: ✨ Feature Request
description: Suggest a new feature or enhancement for aiclip
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a feature! We love hearing your ideas for making aiclip better.

    - type: textarea
      id: problem
      attributes:
          label: Problem or Use Case
          description: What problem does this feature solve? What's your use case?
          placeholder: "I'm trying to... but currently aiclip doesn't support..."
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: How would you like this feature to work?
          placeholder: "I would like aiclip to..."
      validations:
          required: true

    - type: textarea
      id: example
      attributes:
          label: Example Usage
          description: Show how you'd use this feature
          placeholder: |
              aiclip "your example command here"
          render: bash

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: What alternatives have you considered?
          placeholder: "I could work around this by... but it would be better if..."

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Nice to have
              - Would be helpful
              - Important for my workflow
              - Critical/blocking
      validations:
          required: true

    - type: checkboxes
      id: contribution
      attributes:
          label: Contribution
          options:
              - label: I'm willing to help implement this feature
              - label: I can help with testing
              - label: I can help with documentation

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Any other context, mockups, or examples
          placeholder: Add any other context or screenshots about the feature request here...
